# Generated by Django 4.2.11 on 2025-10-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_booking_status_seat_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='show_date',
            field=models.DateField(default='2025-10-10'),
            preserve_default=False,
        ),
    ]
