# Generated by Django 4.2.11 on 2025-10-05 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
