# Generated by Django 4.2.11 on 2025-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_date',
            field=models.DateField(),
        ),
    ]
